import os
import sqlite3
import psycopg
from psycopg import sql

# 1. Configuration
SQLITE_DB = "hardware_inventory.db"
PG_CONN_STRING = os.getenv("SUPABASE_DB_URL", "").strip()
conn = psycopg.connect(PG_CONN_STRING, sslmode="require") if PG_CONN_STRING else None

# Target tables na gustong i-migrate (Kasama na ang borrow_transactions, password_resets, at return_requests)
TARGET_TABLES = [
    "users",
    "hardware",
    "borrow_requests",
    "item_requests",
    "item_holds",
    "borrow_transactions",
    "password_resets",
    "return_requests"
]

def run_migration():
    print("--- Starting Database Migration ---")
    if not PG_CONN_STRING:
        print("SUPABASE_DB_URL is not set. Configure it before running migration.")
        return
    
    try:
        sqlite_conn = sqlite3.connect(SQLITE_DB)
        sqlite_cur = sqlite_conn.cursor()
    except Exception as e:
        print(f"Failed to connect to SQLite: {e}")
        return

    try:
        pg_conn = psycopg.connect(PG_CONN_STRING)
        pg_cur = pg_conn.cursor()
    except Exception as e:
        print(f"Failed to connect to Supabase PostgreSQL: {e}")
        return

    for table_name in TARGET_TABLES:
        try:
            # 1. Kunin ang eksaktong schema/columns mula sa SQLite
            sqlite_cur.execute(f"PRAGMA table_info('{table_name}')")
            columns_info = sqlite_cur.fetchall()

            if not columns_info:
                print(f"Table '{table_name}' does not exist in SQLite database. Skipping.")
                continue

            col_names = [col[1] for col in columns_info]

            # 2. I-drop ang lumang table sa PostgreSQL
            pg_cur.execute(sql.SQL("DROP TABLE IF EXISTS {} CASCADE").format(sql.Identifier(table_name)))

            # 3. Kusa (Dynamically) na buuin ang CREATE TABLE statement
            col_defs = []
            for col in columns_info:
                c_name, c_type, not_null, pk = col[1], col[2].upper(), col[3], col[5]
                
                # Ang totoong Primary Key lang ng SQLite (pk == 1) ang lalagyan ng PRIMARY KEY / IDENTITY
                if pk == 1:
                    if "INT" in c_type or c_name in ["id", "item_id", "request_id", "hold_id", "transaction_id", "reset_id"]:
                        col_defs.append(f"{c_name} BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
                    else:
                        col_defs.append(f"{c_name} TEXT PRIMARY KEY")
                else:
                    # Regular columns at Foreign Keys (walang PRIMARY KEY keyword)
                    pg_type = "TEXT"
                    if "INT" in c_type or c_name.endswith("_id"):
                        pg_type = "BIGINT" if c_name.endswith("_id") else "INTEGER"
                    elif "DOUBLE" in c_type or "FLOAT" in c_type or "REAL" in c_type:
                        pg_type = "DOUBLE PRECISION"
                    elif "BOOL" in c_type:
                        pg_type = "BOOLEAN"

                    null_stmt = " NOT NULL" if not_null else ""
                    col_defs.append(f"{c_name} {pg_type}{null_stmt}")

            create_sql = sql.SQL("CREATE TABLE {} ({})").format(
                sql.Identifier(table_name),
                sql.SQL(", ").join(sql.SQL(c) for c in col_defs)
            )
            pg_cur.execute(create_sql)
            print(f"Table '{table_name}' created dynamically.")

            # 4. Basahin ang data at i-insert sa PostgreSQL
            sqlite_cur.execute(f"SELECT * FROM {table_name}")
            rows = sqlite_cur.fetchall()

            if rows:
                cols_identifier = sql.SQL(", ").join(sql.Identifier(c) for c in col_names)
                placeholders = sql.SQL(", ").join(sql.Placeholder() for _ in col_names)
                
                insert_sql = sql.SQL("INSERT INTO {} ({}) VALUES ({})").format(
                    sql.Identifier(table_name), cols_identifier, placeholders
                )
                
                pg_cur.executemany(insert_sql, rows)
                pg_conn.commit()
                print(f"Successfully migrated {len(rows)} rows into '{table_name}'.")
            else:
                print(f"Table '{table_name}' is empty. 0 rows inserted.")

        except Exception as err:
            pg_conn.rollback()
            print(f"Error migrating table '{table_name}': {err}")

    # Step C: Verification Summary
    print("\n--- Migration Summary ---")
    for table_name in TARGET_TABLES:
        try:
            pg_cur.execute(sql.SQL("SELECT COUNT(*) FROM {}").format(sql.Identifier(table_name)))
            cnt = pg_cur.fetchone()[0]
            print(f" - {table_name}: {cnt} rows")
        except Exception:
            pg_conn.rollback()
            print(f" - {table_name}: Failed to count rows")

    # Close connections
    sqlite_conn.close()
    pg_cur.close()
    pg_conn.close()
    print("\nMigration process finished successfully!")

if __name__ == "__main__":
    run_migration()